In [2]:
class demo1:
    def fact(self,n):
        fact = 1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=demo1()
p1.fact(5)

120

In [3]:
class demo2:
    def accept(self,p1,p2):
        a=p1
        b=p2
        return
    def display(self):
        print("a= ",a)
        print("b= ",b)
c1 = demo2()
c1.accept(10,20)
c1.dispaly()

    

SyntaxError: unexpected EOF while parsing (<ipython-input-3-8a47a43e6a05>, line 7)

In [15]:
class demo2:
    def init(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=demo2()
c1.init(10,20)
print(c1.add(100,200))

300


In [2]:
a1 = np.random.normal(5,1,10)
print(a1)
print("min value = ",np.min(a1))
print("max value = ",np.max(a1))

NameError: name 'np' is not defined

In [6]:
class test:
    def _init_(self,a):
        self.a=a
    def display(self):
         print(self.a)
obj=test()
obj.display()

AttributeError: 'test' object has no attribute 'a'

# python numpy

In [1]:
import numpy as np
list=[1,2,3,4]
array=np.array(list)
print(array)

[1 2 3 4]


In [2]:
import numpy as np
list=[1,2,3,4]
array=np.array(list)
array+10
print(array)

[1 2 3 4]


In [3]:
import numpy as np
array=np.array(list)
print(array.shape)
print(array.dtype)

(4,)
int32


In [4]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [5]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [6]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [7]:
a1=np.random.normal(5,0.5,10)
print(a1)

[5.0972111  5.5749251  5.03471491 5.30600955 4.88966137 5.21290905
 5.09977326 5.13334192 4.58045657 5.31236858]


In [8]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [9]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [10]:
a=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(a)[2]=5
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [11]:

a=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(a)[1][3]=14
np.asarray(a)[3][3]=16
print(a)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [12]:
a1=np.random.normal(5,1,10)
print(a1)
print("min value",np.min(a1))
print("max value",np.max(a1))
print("mean value",np.mean(a1))
print("median value",np.median(a1))

[6.42839846 4.05012125 4.19595901 5.59178802 4.93327645 3.82886056
 4.23787515 5.02833148 5.91172296 6.83251547]
min value 3.8288605558370437
max value 6.832515470060148
mean value 5.103884879128117
median value 4.9808039643731


In [13]:

c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [14]:
a=np.array([1,2,3,5,8])
b=np.array([0,3,4,2,1])
c=a+b
c=c*a
print(c[2])

21


In [15]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])